-- AI Ads Manager v2 Schema

-- 1. ad_clicks: Track every entrance to the landing page
CREATE TABLE IF NOT EXISTS ad_clicks (
    click_id TEXT PRIMARY KEY, -- From Propeller URL param ?click_id=...
    zone_id TEXT,
    creative_id TEXT,
    campaign_id TEXT,
    visitor_ip TEXT,
    user_agent TEXT,
    device_fingerprint TEXT, -- Optional, from frontend JS
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. conversions: "Truth" data from landing page actions
CREATE TABLE IF NOT EXISTS conversions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    click_id TEXT REFERENCES ad_clicks(click_id),
    event_type TEXT CHECK (event_type IN ('registration', 'deposit', 'login')),
    amount DECIMAL(10, 2), -- For deposits
    currency TEXT DEFAULT 'KES',
    verification_status TEXT DEFAULT 'pending', -- 'verified' if we get postback
    time_on_page INTEGER, -- Seconds spent before conversion
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. ai_logs: Transparency log for all AI actions
CREATE TABLE IF NOT EXISTS ai_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    category TEXT CHECK (category IN ('creative', 'zone', 'budget', 'learning', 'fraud', 'experiment', 'execution')),
    action TEXT, -- 'paused', 'blocked', 'bid_change', 'recommendation'
    description TEXT,
    entity_affected TEXT, -- 'zone_123', 'creative_456'
    reasoning TEXT,
    confidence_score INTEGER,
    data_snapshot JSONB, -- Store the metrics that led to this decision
    execution_result TEXT -- 'success', 'failed', 'pending_approval'
);

-- 4. ai_patterns: Learned insights
CREATE TABLE IF NOT EXISTS ai_patterns (
    pattern_key TEXT PRIMARY KEY, -- e.g., "creative_angle_bigwin_zone_safaricom_evening"
    pattern_data JSONB, -- { "angle": "big_win", "carrier": "safaricom", "hours": [21,22,23] }
    performance_metrics JSONB, -- { "roi": 2.5, "conversion_rate": 0.05 }
    confidence_score INTEGER,
    last_validated TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    times_seen INTEGER DEFAULT 1
);

-- 5. zones: Metadata and scoring for zones
CREATE TABLE IF NOT EXISTS zones (
    zone_id TEXT PRIMARY KEY,
    status TEXT DEFAULT 'active', -- 'active', 'blocked', 'whitelisted'
    fraud_score INTEGER DEFAULT 0,
    quality_tier TEXT DEFAULT 'unknown', -- 'premium', 'high', 'acceptable', 'low', 'trash'
    last_analyzed TIMESTAMP WITH TIME ZONE
);

-- 6. creatives: Metadata and scoring for creatives
CREATE TABLE IF NOT EXISTS creatives (
    creative_id TEXT PRIMARY KEY,
    angle TEXT,
    language TEXT,
    status TEXT DEFAULT 'active', -- 'active', 'paused'
    fraud_score INTEGER DEFAULT 0,
    fatigue_detected BOOLEAN DEFAULT FALSE,
    last_analyzed TIMESTAMP WITH TIME ZONE
);

-- 7. ab_tests: Experimentation Engine
CREATE TABLE IF NOT EXISTS ab_tests (
    test_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_type TEXT CHECK (test_type IN ('CREATIVE', 'ZONE', 'BID')),
    status TEXT DEFAULT 'RUNNING',  -- CHECK (status IN ('RUNNING', 'CONCLUDED')) - simplified for compatibility
    start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    end_date TIMESTAMP WITH TIME ZONE,
    
    -- entities being tested (JSON array of IDs)
    candidates JSONB, 
    
    -- snapshot of metrics at start of test for comparison
    start_metrics JSONB,
    
    -- result
    winner_id TEXT,
    improvement_pct DECIMAL(5,2),
    confidence_score INTEGER
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_ad_clicks_created_at ON ad_clicks(created_at);
CREATE INDEX IF NOT EXISTS idx_conversions_created_at ON conversions(created_at);
CREATE INDEX IF NOT EXISTS idx_ai_logs_timestamp ON ai_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_ab_tests_status ON ab_tests(status);
