-- AI Ads Manager v2 Schema Update: Propeller Stats

-- 7. propeller_daily_stats: Sync Propeller API data for comparison
CREATE TABLE IF NOT EXISTS propeller_daily_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    zone_id TEXT,
    creative_id TEXT, -- Optional, if we get granular stats
    campaign_id TEXT,
    impressions INTEGER DEFAULT 0,
    clicks INTEGER DEFAULT 0,
    conversions INTEGER DEFAULT 0, -- Propeller's count (fake?)
    spend DECIMAL(10, 4) DEFAULT 0, -- Cost
    ctr DECIMAL(5, 4),
    cpa DECIMAL(10, 2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(date, zone_id, campaign_id) -- Prevent duplicates
);

-- Index for querying by date
CREATE INDEX IF NOT EXISTS idx_propeller_daily_stats_date ON propeller_daily_stats(date);
