-- Create the landing_stats table if it doesn't exist
create table if not exists landing_stats (
    id bigint generated by default as identity primary key,
    session_id text not null,
    action text not null CHECK (action IN ('visit', 'click')),
    referrer text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for faster queries
create index if not exists landing_stats_created_at_idx on landing_stats (created_at);
create index if not exists landing_stats_action_idx on landing_stats (action);
