-- Activities Table (Real-time feed)
CREATE TABLE IF NOT EXISTS activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  type TEXT, -- 'budget_change', 'creative_action', etc.
  severity TEXT, -- 'info', 'warning', 'critical', 'success'
  icon TEXT,
  message TEXT,
  details JSONB,
  user_visible BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_activities_timestamp ON activities(timestamp DESC);

-- Audits Table (10-minute reports)
CREATE TABLE IF NOT EXISTS audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  period_start TIMESTAMP WITH TIME ZONE,
  period_end TIMESTAMP WITH TIME ZONE,
  
  -- Metrics
  impressions_current INTEGER,
  impressions_previous INTEGER,
  clicks_current INTEGER,
  clicks_previous INTEGER,
  ctr_current DECIMAL(5,2),
  ctr_previous DECIMAL(5,2),
  spend_current DECIMAL(10,2),
  conversions_current INTEGER,
  epc_current DECIMAL(10,4),
  roi_current DECIMAL(10,2),
  
  -- Analysis
  creative_analysis JSONB,
  zone_analysis JSONB,
  budget_check JSONB,
  recommendations JSONB,
  
  -- Health
  health_score INTEGER,
  
  -- Actions
  actions_taken JSONB
);

CREATE INDEX IF NOT EXISTS idx_audits_timestamp ON audits(timestamp DESC);

-- Decisions Table (All AI decisions)
CREATE TABLE IF NOT EXISTS decisions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  decision_type TEXT, -- 'approved', 'rejected', 'paused', etc.
  entity_type TEXT, -- 'budget', 'creative', 'zone'
  entity_id TEXT,
  decision TEXT,
  reasoning TEXT,
  impact TEXT,
  supporting_data JSONB,
  executed BOOLEAN DEFAULT FALSE,
  execution_timestamp TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_decisions_timestamp ON decisions(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_decisions_type ON decisions(decision_type);

-- Processes Table (Current running processes)
-- Note: Vercel functions are ephemeral, so "RUNNING" status might be short-lived.
-- We will use this to show "Last Ran" or "Current State" if we update it frequently during execution.
CREATE TABLE IF NOT EXISTS processes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE,
  description TEXT,
  status TEXT, -- 'RUNNING', 'COMPLETE', 'FAILED'
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  progress INTEGER DEFAULT 0,
  substeps JSONB,
  result JSONB
);
