-- RUN THIS IN YOUR SUPABASE SQL EDITOR TO SETUP THE DATABASE

-- 1. CREATIVES TABLE
CREATE TABLE IF NOT EXISTS creatives (
    creative_id TEXT PRIMARY KEY,
    campaign_id TEXT,
    title TEXT,
    description TEXT,
    emoji_set TEXT,
    language TEXT, -- 'sheng', 'swahili', 'english'
    angle TEXT, -- 'fomo', 'bonus', 'curiosity'
    status TEXT, -- 'active', 'paused', 'testing', 'killed'
    ctr NUMERIC,
    epc NUMERIC,
    conversion_rate NUMERIC,
    total_impressions INTEGER,
    total_clicks INTEGER,
    total_conversions INTEGER,
    total_spend NUMERIC,
    performance_score NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_tested_at TIMESTAMP WITH TIME ZONE
);

-- 2. ZONES TABLE
CREATE TABLE IF NOT EXISTS zones (
    zone_id TEXT PRIMARY KEY,
    traffic_source TEXT,
    avg_ctr NUMERIC,
    avg_epc NUMERIC,
    quality_score NUMERIC,
    total_impressions INTEGER,
    total_clicks INTEGER,
    total_conversions INTEGER,
    total_spend NUMERIC,
    status TEXT, -- 'allowed', 'blocked', 'whitelisted'
    device_primary TEXT,
    blocked_at TIMESTAMP WITH TIME ZONE,
    whitelisted_at TIMESTAMP WITH TIME ZONE,
    last_seen TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. PERFORMANCE HISTORY (Creative x Zone)
CREATE TABLE IF NOT EXISTS performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creative_id TEXT REFERENCES creatives(creative_id),
    zone_id TEXT REFERENCES zones(zone_id),
    date DATE DEFAULT CURRENT_DATE,
    hour INTEGER,
    impressions INTEGER,
    clicks INTEGER,
    conversions INTEGER,
    spend NUMERIC,
    device_type TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. BUDGET LOGS
CREATE TABLE IF NOT EXISTS budget_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id TEXT,
    change_type TEXT, -- 'increase', 'decrease', 'cut'
    amount NUMERIC,
    reason TEXT,
    ctr_at_time NUMERIC,
    roi_at_time NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. VISITS & CLICKS (Legacy/Tracker Support)
CREATE TABLE IF NOT EXISTS visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id TEXT,
    zone_id TEXT,
    creative_id TEXT,
    device TEXT,
    user_agent TEXT,
    ip_hash TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id BIGINT REFERENCES visits(id),
    creative_id TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id BIGINT REFERENCES visits(id),
    phone TEXT,
    amount NUMERIC,
    status TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
